name: Reflex Deploy Action
description: Deploy Reflex apps to Reflex Cloud.
inputs:
  auth_token:
    description: Reflex authentication token (stored as a secret).
    required: true
  project_id:
    description: The ID of the Reflex project to deploy to (stored as a secret).
    required: true
  app_directory:
    description: The subfolder containing the Reflex app (default is root).
    required: false
    default: "."
  extra_args:
    description: Additional arguments to pass to the Reflex CLI.
    required: false
branding:
  icon: upload-cloud
  color: purple

runs:
  using: "composite"
  steps:
    - name: Deploy Reflex App
      shell: bash
      working-directory: ${{ inputs.app_directory }}
      run: reflex deploy --token ${{ inputs.auth_token }} --project ${{ inputs.project_id }} --no-interactive  ${{ inputs.extra_args }}
